FROM python:3.12

ENV GRADIO_SERVER_NAME=0.0.0.0
ENV PIP_BREAK_SYSTEM_PACKAGES=1

WORKDIR /facefusion

RUN apt-get update
RUN apt-get install curl -y
RUN apt-get install ffmpeg -y

ARG CACHE_BUST=1
RUN echo "Cache bust: $CACHE_BUST" && \
    git clone https://github.com/fevolq/facefusion.git --single-branch .

RUN python install.py --onnxruntime default --skip-conda
