services:
 facefusion-cpu:
  build:
   context: .
   dockerfile: Dockerfile.cpu
  image: facefusion:${IMAGE_TAG:-cpu}
  command: [ 'python', 'facefusion.py', '${MODE:-run}', '--execution-providers', 'cpu', '--log-level', '${LOG_LEVEL:-info}' ]
  volumes:
  - .assets:/facefusion/.assets
  - .caches:/facefusion/.caches
  - .jobs:/facefusion/.jobs
  - ./data:/facefusion/data
  ports:
  - ${EXPOSE_PORT:-7860}:7860
