services:
 facefusion-cuda:
  build:
   context: .
   dockerfile: Dockerfile.cuda
  image: facefusion:${IMAGE_TAG:-cuda}
  command: [ 'python', 'facefusion.py', '${MODE:-run}', '--execution-providers', 'cuda', '--log-level', '${LOG_LEVEL:-info}' ]
  volumes:
  - .assets:/facefusion/.assets
  - .caches:/facefusion/.caches
  - .jobs:/facefusion/.jobs
  - ./data:/facefusion/data
  ports:
  - ${EXPOSE_PORT:-7860}:7860
  deploy:
   resources:
    reservations:
     devices:
     - driver: nvidia
       capabilities: [ gpu, video ]
       device_ids: ['${DEVICE:-0}']
